version: '2'
services:
  campus-app:
    image: campus
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://campus-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=campus
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://campus-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://campus-elasticsearch:9200
    ports:
      - 8080:8080
  campus-mongodb:
    extends:
      file: mongodb.yml
      service: campus-mongodb
  campus-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: campus-elasticsearch
